#!/usr/bin/python
#

import urllib2
import os

fd = open(os.environ.get("HOME") + "/.fh/feedlist", "r")

if fd == -1:
   print "error : unable to find ~/.fh/feedlist. You should probably run fh-setup"
   os.exit()

i = 0

for line in fd.readlines():
    request = urllib2.Request(url = line.rstrip())
    feed = urllib2.urlopen(request).read()

    fname = line.replace("http://", "")
    fname = fname.replace("/", "-")
    fname = fname.replace('\n', '')
    feedfd = open(os.environ.get("HOME") + "/.fh/feeds/" + fname, "w+")
    feedfd.write(feed)
    i += 1

print "Fetched ", i, " feed(s)"
